"""Canonical model-independent UI flows for runtime-security demonstrations.

These explanations are rendered by the application, not generated by the LLM. This
keeps the PoC explanation stable when the underlying Claude model is changed.
"""

RUNTIME_FLOWS = {
    "Tool Permission": {
        "title": "Tool Permission Flow",
        "caption": (
            "The LLM may request a tool call, but runtime permission decides whether "
            "the underlying tool handler is allowed to execute."
        ),
        "flow": (
            "User Input\n"
            "    ↓\n"
            "LLM / Agent reasoning\n"
            "decides the delete_digest tool is needed\n"
            "    ↓\n"
            "Tool call request created: delete_digest(...)\n"
            "    ↓\n"
            "┌──────────────────────────────────┐\n"
            "│       TOOL PERMISSION POLICY     │\n"
            "│  Is delete_digest authorized?    │\n"
            "└──────────────────────────────────┘\n"
            "    ↓\n"
            "NOT APPROVED\n"
            "    ↓\n"
            "BLOCKED before real handler executes\n"
            "    ↓\n"
            "LLM receives the runtime block result\n"
            "    ↓\n"
            "LLM summarizes the block reason to user"
        ),
    },
    "Allowed Egress": {
        "title": "Egress Control Flow — Allowed",
        "caption": (
            "The LLM proposes a network-capable tool call. Runtime egress policy checks "
            "the destination before the real network request is made."
        ),
        "flow": (
            "User Input\n"
            "    ↓\n"
            "LLM / Agent reasoning\n"
            "decides external data is needed\n"
            "    ↓\n"
            "Tool call request created\n"
            "get_trending_repos(endpoint=api.github.com, ...)\n"
            "    ↓\n"
            "┌──────────────────────────────────┐\n"
            "│          EGRESS CONTROL          │\n"
            "│  Is destination host approved?   │\n"
            "└──────────────────────────────────┘\n"
            "    ↓\n"
            "api.github.com IS APPROVED\n"
            "    ↓\n"
            "ALLOWED\n"
            "    ↓\n"
            "Real network tool executes\n"
            "    ↓\n"
            "Tool result returns to LLM\n"
            "    ↓\n"
            "LLM summarizes the result to user"
        ),
    },
    "Blocked Egress": {
        "title": "Egress Control Flow — Blocked",
        "caption": (
            "A legitimate destination can still be denied when it is outside the "
            "application's explicitly approved egress policy."
        ),
        "flow": (
            "User Input\n"
            "    ↓\n"
            "LLM / Agent reasoning\n"
            "decides fetch_news is needed\n"
            "    ↓\n"
            "Tool call request created\n"
            "fetch_news(url=arstechnica.com/...)\n"
            "    ↓\n"
            "┌──────────────────────────────────┐\n"
            "│          EGRESS CONTROL          │\n"
            "│  Is destination host approved?   │\n"
            "└──────────────────────────────────┘\n"
            "    ↓\n"
            "arstechnica.com IS NOT APPROVED\n"
            "    ↓\n"
            "BLOCKED before real network request\n"
            "    ↓\n"
            "LLM receives the runtime block result\n"
            "    ↓\n"
            "LLM summarizes the block reason to user"
        ),
    },
    "Secret Protection": {
        "title": "Secret Protection Data Flow",
        "caption": (
            "Secret Protection is enforced between the LLM's requested action and "
            "actual tool execution."
        ),
        "flow": (
            "User Input\n"
            "    ↓\n"
            "LLM / Agent\n"
            "obtains controlled synthetic credential\n"
            "    ↓\n"
            "LLM decides to call save_digest(...)\n"
            "    ↓\n"
            "Tool name + arguments generated\n"
            "    ↓\n"
            "┌──────────────────────────────────┐\n"
            "│       SECRET PROTECTION          │\n"
            "│  Scan tool-call arguments before │\n"
            "│  the tool is allowed to execute  │\n"
            "└──────────────────────────────────┘\n"
            "    ↓\n"
            "Protected secret detected?\n"
            "      /              \\\n"
            "    YES               NO\n"
            "     ↓                 ↓\n"
            "   BLOCK            CONTINUE\n"
            "     ↓                 ↓\n"
            "Tool is NOT       Tool executes\n"
            "executed          normally\n"
            "     ↓\n"
            "LLM receives block result and summarizes it"
        ),
    },
    "Content Trust": {
        "title": "Content Trust Flow",
        "caption": (
            "Content Trust checks untrusted tool output before that external content "
            "is returned to the LLM for normal use."
        ),
        "flow": (
            "User Input\n"
            "    ↓\n"
            "LLM / Agent reasoning\n"
            "decides fetch_news is needed\n"
            "    ↓\n"
            "Tool call passes permission / egress checks\n"
            "    ↓\n"
            "Real fetch_news tool executes\n"
            "    ↓\n"
            "External article content returned\n"
            "    ↓\n"
            "┌──────────────────────────────────┐\n"
            "│          CONTENT TRUST           │\n"
            "│ Scan external/tool output before │\n"
            "│ normal model-context use         │\n"
            "└──────────────────────────────────┘\n"
            "    ↓\n"
            "Instruction-shaped content detected?\n"
            "      /              \\\n"
            "    YES               NO\n"
            "     ↓                 ↓\n"
            "   BLOCK          Return content\n"
            "     ↓            to LLM normally\n"
            "Suspicious content is NOT exposed\n"
            "for normal model use\n"
            "     ↓\n"
            "LLM receives the structured block result\n"
            "     ↓\n"
            "LLM summarizes the block reason to user"
        ),
    },
}


def get_runtime_flow(scenario: str) -> dict | None:
    """Return the canonical explanatory flow for a runtime demo scenario."""
    return RUNTIME_FLOWS.get(scenario)
